FROM golang:1.16-alpine

RUN apk update && apk add git && go get github.com/gorilla/websocket

WORKDIR /exchange

COPY /exchange/go.mod ./
COPY /exchange/go.sum ./
RUN go mod download

COPY /exchange/*.go ./
